#!/bin/bash
#+--------------------------------------------------------------------------+
#
# onecons - show console data for one user ID 
# Sample URL:  zlnx1.example.com/zlmarw/onecons?TCPIP&LPAR1
#
#+--------------------------------------------------------------------------+
# global variables:
userID=`echo $QUERY_STRING | awk -F'&' '{print $1}'`   # user ID is arg 1 
systemID=`echo $QUERY_STRING | awk -F'&' '{print $2}'` # system ID is arg 2
option=`echo $QUERY_STRING | awk -F'&' '{print $3}'`   # option such as spool 
title="Console of $userID at $systemID"                # page title

# main()
source consuifuncs                         # import common Web UI functions
startPage                                  # start the Web page
cat consolez.css                           # inline CSSs 
checkUser 
showOneConsole $userID $systemID $option   # do the work 
drawButtons                                # add buttons at bottom

