#!/bin/bash
#
# countzlma - count lines of the zlma code
# 
SBN="/usr/local/sbin"
ZRW="/srv/www/zlmarw"
python="/srv/www/zlma/finder.py /srv/www/zlma/restapi.py $SBN/zlma $SBN/zlma_conf.py $SBN/vif"
javascript="/srv/www/zlma/bootstable.js"
bash="$HOME/zlmainfo $SBN/test* $SBN/spoolcons $SBN/cpcommand $SBN/consfuncs $SBN/qprivclas \
  $ZRW/one* $ZRW/consolez $ZRW/searchcons $ZRW/cpcmds $ZRW/consuifuncs"
css="/srv/www/zlma/zlma.css"
 
echo
echo "Lines of code in zlma:"
echo
echo "Bash:"
wc -l $bash
echo
echo "Python:"
wc -l $python
echo
echo "Javascript:"
wc -l $javascript
echo
echo "CSS:"
wc -l $css
echo
# get total lines
wc -l $python $javascript $bash $css | tail -1 | sed 's/^  //g'
